namespace Domain.Enums;
public enum Regio
{
    Zuid_Holland_Zuid,
    Amsterdam,
    Brabant_Zuidoost,
    Drente,
    Flevoland,
    Fryslân,
    Gerderland_Zuid,
    Gooi_en_Vechtstreek,
    Groningen,
    Haaglanden,
    Hart_voor_Brabant,
    Hollands_Midden,
    Hollands_Noorden,
    Ijsselland,
    Kennemerland,
    Limburg_Noord,
    Noord__en_Oost_Gelderland,
    regio_Utrecht,
    Rotterdam_Rijnmond,
    Twente,
    West_Brabant,
    Zaanstreek_Waterland,
    Zeeland,
    Zuid_Limburg,
    Gelderland_Midden
}